version : "3"

services:
  nginx:
		build:
			context: ./requirements/nginx
		image: nginx
		container_name: nginx_container
    ports:
      - "443:443"
		environment: 
			-
		

	mariadb:
		build:
			context: ./requirements/mariadb
		image: mariadb
		container_name: mariadb_container
		environment:
			- MYSQL_ROOT_PASSWORD: $(MYSQL_ROOT_PASSWORD)
			- MYSQL_DATABASE: $(MYSQL_DATABASE)
			- MYSQL_USER: $(MYSQL_USER)
			- MYSQL_PASSWORD: $(MYSQL_PASSWORD)
		volumes:
			- mariadb-data:/var/lib/mysql
		restart: unless-stopped

	wordpress:
		depends_on:
			- mariadb
		build:
			context: ./requirements/wordpress
		image: wordpress
		container_name: wordpress_container
		environment: 
			-
		volumes:
			-
		restart: unless-stopped
